### ISSUE TITLE
Needs manual page

### ISSUE THREAD

**Issue by ExcaliburZero** [kevr/sprunge#1]
Currently the program does not have a manual page, thus a manual page should be created for it in order to help remind users on how to use the program.

**Comment by kevr** [comment]
Will do within the next day or two here- Sorry for the late reply, I've been tremendously busy lately.

**Comment by kevr** [comment]
...I never ended up doing this, totally forgot about it. Will put this on an immediate roadmap.

**Comment by kevr** [comment]
https://github.com/kevr/sprunge/issues/4
