### ISSUE TITLE
The sprunge web site no longer works

### ISSUE THREAD

**Issue by fryfrog** [kevr/sprunge#2]
Looks like the web site sprunge is hosted on exceeds some quota and isn't often online anymore.

![Screen Shot 2019-09-03 at 11 15 59 AM](https://user-images.githubusercontent.com/87748/64197988-3986b580-ce3c-11e9-8765-281fabc1e76d.png)

**Comment by kevr** [comment]
Indeed. It seems to go down constantly. Unfortunate, but I don't own the site and I can't do anything myself.
