### ISSUE TITLE
[FEATURE] Optional paste ID as input

### ISSUE THREAD

**Issue by GaKu999** [kevr/sprunge#3]
### **What:**
The actual arg syntax doesn't use any non-option arg.
There's a chance to use an optional ID to make sprunge fetch a paste instead of posting from stdin.

### **Why:**
It would be a neat replacement of 
`curl 'http://sprunge.us/<ID>'`
using the builtin capability of python.

**Comment by kevr** [comment]
Sounds like a quite useful option to me; will produce a PR regarding this soon!

**Comment by kevr** [comment]
@GaKu999 Created a PR at https://github.com/kevr/sprunge/pull/6 regarding this feature. Could you please test it and report your findings?

```
$ git fetch origin --all
$ git checkout -b issue-3
$ git reset --hard origin/issue-3
$ ./sprunge --help
```

**Comment by GaKu999** [comment]
It looks good and works as expected.
Since the patch is merged already I'll be closing this.

**Comment by kevr** [comment]
Haha, just merged it a couple of minutes earlier :)
