### ISSUE TITLE
http://sprunge.us is currently offline: "Error: Page not found The requested URL was not found on this server."

### ISSUE THREAD

**Issue by holta** [kevr/sprunge#8]
Does anyone know why the [sprunge.us](http://sprunge.us) site is no longer working?  Browsers shos:

![image](https://github.com/kevr/sprunge/assets/2458907/fc2ea40e-ca51-428c-b406-5fdd8ec81284)

(Or perhaps you might know if this is being worked on ?)

Grateful!

🙏

**Comment by holta** [comment]
From the command-line, running `pastebinit -b sprunge.us <FILE>` now fails, with this error that didn't occur in the past:

```
Failed to contact the server: <urlopen error [Errno 32] Broken pipe>
```

![image](https://github.com/kevr/sprunge/assets/2458907/56f7ba29-e0cc-4165-8569-37501532b2d0)

**Comment by tess-ss** [comment]
Hi team,

The issue still exists and not seem to be fixed.

Thanks,
@tess-ss

**Comment by kevr** [comment]
> Does anyone know why the [sprunge.us](http://sprunge.us) site is no longer working? Browsers shos:
> 
> ![image](https://private-user-images.githubusercontent.com/2458907/257018425-fc2ea40e-ca51-428c-b406-5fdd8ec81284.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzNDA1NDQsIm5iZiI6MTcxODM0MDI0NCwicGF0aCI6Ii8yNDU4OTA3LzI1NzAxODQyNS1mYzJlYTQwZS1jYTUxLTQyOGMtYjQwNi01ZmRkOGVjODEyODQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MTRUMDQ0NDA0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDQxY2JjM2E1MjFkZmU2NTJmYjliYjg0YWU4Mjc0NjI0MmZmNjdjMDk2MDQ0YjFjMTgzNmY3NGFmYWE0ZmIzNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.bGIuMxtJY4O8Ey9KjGbxXvWDAuhTLy8GnVp1v7k_QLo)
> 
> (Or perhaps you might know if this is being worked on ?)
> 
> Grateful!
> 
> 🙏

Unfortunately, I have no clue. I just wrote the script some time ago, this website is run by another. Hope they bring it back up, love the simplicity of sprunge.

**Comment by holta** [comment]
Thank you @kevr.

Sadly sprunge.us began failing again about a month ago, and so for now, we've decided to use dpaste.com instead:

- https://github.com/iiab/iiab/pull/3748

**Comment by kevr** [comment]
> Thank you @kevr.
> 
> Sadly sprunge.us began failing again about a month ago, and so for now, we've decided to use dpaste.com instead:
> 
> * [Let's try pastebin service dpaste.com (limited to 30 days, and ~1,000,000 characters unfortunately) — instead of problematic (flaky) sprunge.us iiab/iiab#3748](https://github.com/iiab/iiab/pull/3748)

Indeed, you should use another service is sprunge is down.

Some other's I would suggest is: paste.rs, ix.io

I believe there are clients around for both of those if needed, otherwise, curl can be used pretty simply to achieve what this script does for sprunge.

As long as sprunge.us is down, this particular project is going to be dead.
